language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
env:
  global:
    - SFTP_KEY=test
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"
    - DISPLAY=":99.0"
    - APPLICATION_ENV=testing
    - ZEND_BACKEND="--backend=ZendEngine3" PHALCON_VERSION="v3.0.0"
    - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
    - 'SFTP_KEY=[base64-encoded-rsa-key]' 
    
cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_script:
    # Disable xdebug
  - phpenv config-rm xdebug.ini
    # Extend PHP memory
  - phpenv config-add travis.php.ini
    #- echo "memory_limit=520M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    # Install composer packages
  - php -r "print(ini_get('memory_limit'));"
  - composer install --prefer-source --no-interaction
    # Install Phalcon
  - vendor/bin/install-phalcon.sh 3.0.x
  
script:
  - vendor/bin/phpunit
  
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T filename
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename
       
notifications:
  email: false


