sudo: required
language: php
services:
  - docker

php:
  - 5.5
  - 5.6
  - 7.0
env:
  global:
    - SFTP_KEY=test
    - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
    - 'SFTP_KEY=[base64-encoded-rsa-key]' 
    
cache:
  directories:
    #- vendor
    #- ~/.composer/cache

before_install:
  - docker build . -t apacs/test
  - docker run -d --name app apacs/test
  
script:
  - docker exec app phpunit
  
after_script:
  - docker rm -f app
  
after_success:
#- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
#- curl --ftp-create-dirs
#       -T filename
#       --key /tmp/sftp_rsa
#       sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename
       
notifications:
  email: false


