language: php
dist: trusty

php:
  - 5.6
git:
  depth: 1
cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache
env:
  global:
    - SFTP_KEY=test
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"
    - DISPLAY=":99.0"
    - APPLICATION_ENV=testing
    - ZEND_BACKEND="--backend=ZendEngine3" PHALCON_VERSION="v3.0.0"
before_script: phpenv config-add 30-phalcon.ini    
#script: phpunit --configuration phpunit.xml
script: false
before_install:
  - curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | sudo bash
  - sudo apt-get update
install:
  - sudo apt-get install php5-phalcon
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  - travis_retry composer require --dev "phalcon/zephir:0.9.11" --ignore-platform-reqs
    global:
  - 'SFTP_USER=[user]'
    - 'SFTP_PASSWORD=[password]'
  - 'SFTP_KEY=[base64-encoded-rsa-key]'
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T filename
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@example.com/directory/filename
