sudo: required
language: php
services:
  - docker

php:
  - 7.0
    
cache:
  directories:
    #- vendor
    #- ~/.composer/cache

before_install:
  - docker build . -t apacs/test

  
script:
  - docker run -d --name app apacs/test phpunit --help
  
after_script:
  - docker rm -f app
  
after_success:
  - curl --ftp-create-dirs --upload-file "." ftp://${FTP_USER}:${FTP_PASSWORD}@kbhkilder.dk/1508/test_deploy
       
notifications:
  email: false
