sudo: required
language: php
services:
  - docker

php:
  - 7.0
    
cache:
  directories:
    #- vendor
    #- ~/.composer/cache

before_install:
  - docker pull stumpdk/apacs_unit_test_platform

  
script:
  - docker run stumpdk/apacs_unit_test_platform /vendor/phpunit/phpunit/phpunit --bootstrap tests/TestHelper.php --testdox tests
  
after_script:
  - docker rm -f app
  
after_success:
  - ls -l
  - curl --ftp-create-dirs --upload-file "{.}" ftp://${FTP_USER}:${FTP_PASSWORD}@phhw-140602.cust.powerhosting.dk/1508/test_deploy/
       
notifications:
  email: false
